import 'dart:math';

//Generated by Copilot
String passGenerator(int length) {
  const String lowerCase = 'abcdefghijklmnopqrstuvwxyz';
  const String upperCase = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
  const String numbers = '0123456789';
  const String symbols = '!@#%^&*()_+';
  const String all = lowerCase + upperCase + numbers + symbols;

  String password = '';

  for (int i = 0; i < length; i++) {
    password += all[Random().nextInt(all.length)];
  }

  return password;
}
